### ISSUE TITLE
Installing instantpage removes edit buttons from edit window

### ISSUE THREAD

**Issue by bactram** [micgro42/dokuwiki-plugin-instantpage#3] opened 2019-04-20 16:47 UTC
I installed this and the buttons on the edit window disappeared. Disabling the plugin brought the buttons back. I'm running the latest version of dokuwiki. 

![see what i mean](https://user-images.githubusercontent.com/26173311/56460043-5c6f6c00-636a-11e9-8158-5374df4c2222.png)

**Comment by micgro42** [comment] 2019-04-20 17:38
This means that there is a javascript error, most likely caused by DokuWiki's javascript compression being old. Which means that this is has likely the same cause as and thus is a duplicate of #2 

I just released a new version of the plugin. Please update and see if it improves your issue.

**Closed as completed by micgro42** 2019-04-20 17:38 UTC
Labels: bug, duplicate

**Comment by bactram** [comment] 2019-04-20 18:25
Yes. I just installed again, and it's working fine. Thank you for explaining what happened.
